[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

remappings = [
    'forge-std/=lib/forge-std/src/',
    '@openzeppelin/=lib/openzeppelin-contracts/',
    "@tokenized-strategy/=lib/tokenized-strategy/src/",
    "@yearn-vaults/=lib/yearn-vaults-v3/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config